### ISSUE TITLE
Proper Use to Get Single Cell Whole-Word Contractions

### ISSUE THREAD

**Issue by jmwright** [ant0nisk/pyUniBraille#5]
I'm having trouble getting an expected result. I assume that calling `translate` on the word `knowledge` should return just the letter `k`, correct? I get this result instead.

```python
>>> import pybrl as brl
>>> brl.translate("knowledge")
[['101000', '101110', '010101', '111000', '110101', '100010', '110110']]
>>> brl.preprocess("knowledge")
[['k', 'n', 'ow', 'l', 'ed', 'e', 'g']]
```

I see similar behavior if I use another word like `but`. I looked through the tests, but did not notice anything for single cell whole-word contractions. like this.

**Comment by jmwright** [comment]
The core issue here is that sometimes the preprocessor is rearranging letter orders, and so the check in the code [here](https://github.com/ant0nisk/pybrl/blob/master/pybrl.py#L244) fails.

For example, with the word `knowledge`, the preprocessor is returning `['k', 'n', 'ow', 'l', 'ed', 'e', 'g']`, which when joined using the line of code I linked leads to the misspelling `knowledeg` and so the check to see if the word is a single cell contraction fails.

**Comment by ant0nisk** [comment]
Hi Jeremy,

Sorry for the (very) late reply, I somehow did not get a notification about this thread.
Did you manage to resolve the issue? I see you forked the repo and made some nice additions.

If you like you can make a pull request and I can merge it back here ;)

In the meantime, if you haven't figured out yet why the preprocessor returns it out of order, I can have a brief look to see what's wrong.

Best regards,
Antonis

**Comment by jmwright** [comment]
@ant0nisk I ended up going a different route for my 3D printed braille generator, and so never finished the fix for this issue. My comment from September 4th highlights the issue though, or at least I think it does.

I can create a PR for the changes that I made if you want to review.

**Comment by ant0nisk** [comment]
I found the issue and fixed it. I have to say that looking into my 6 year old code from my teenage years caused me some headache xD

Can you create a PR? I've seen the changes and they are good.
I will merge that one first and then check if your unit-test for the contraction also works with the new fix.

Thanks for showing interest in this project. I hope your braille generator worked out ;)

**Comment by jmwright** [comment]
> I have to say that looking into my 6 year old code from my teenage years caused me some headache

Looking back at old code has that effect on me too.

> Can you create a PR? I've seen the changes and they are good.

Done: #7 

> I hope your braille generator worked out ;)

The code for that generator is [here](https://codeberg.org/7BIndustries/braille-label-generator). There is a download page [here](https://7bindustries.com/hardware/braille_download.html) where you can input the text you want on the braille label and then it gives you a 3D printable STL file. I ended up using liblouis for that generator. However, I like the simpler nature of this library and that it is written completely in Python. The output it gives is also a great fit for translation into a 3D model. If I get time I'll come back to this project and see about using it again.

**Comment by ant0nisk** [comment]
Alright, fixed! Thanks a lot for raising the issue.
I'll keep an eye on your generator. Looks like a neat project ;)

Cheers!
