### ISSUE TITLE
AttributeError: module 'pybrl' has no attribute 'translate'

### ISSUE THREAD

**Issue by amunozo** [ant0nisk/pyUniBraille#6]
Hi! I am trying to use the library. I installed the dependencies and the library is imported correctly. However, when trying to replicate the example available at the repo, I get this:
`AttributeError: module 'pybrl' has no attribute 'translate'`

How can I fix it?

**Comment by ant0nisk** [comment]
Hi, are you perhaps using it from one directory up? What if you try to import from the same directory as the file pybrl.py?

**Comment by ant0nisk** [comment]
Closing as stale question
